# Generated by Django 4.1 on 2022-11-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_autor_livro"),
        ("core", "0003_livro_autores"),
    ]

    operations = []
