# Generated by Django 4.1.2 on 2022-11-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_livro_capa"),
        ("core", "0005_livro_autores_alter_livro_preco_and_more"),
    ]

    operations = []
